### ISSUE TITLE
Operation select not implemented.

### ISSUE THREAD

**Issue by mxandeco** [fppt/jedis-mock#10]
Trying to migrate a current `embedded-redis` to `jedis-mock` and having the error:

```java
redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'select'
```

Is something that can be added to `jedis-mock`?

**Comment by fppt** [comment]
The mock currently does not support that command. I will add it to my todo and get to it when I can. I will also make that error message more clear so it's obvious this is a current limitation on the mock.

**Comment by fppt** [comment]
This is being addressed in https://github.com/fppt/jedis-mock/pull/16

**Comment by fppt** [comment]
This is now supported: https://github.com/fppt/jedis-mock/releases/tag/v0.1.9
