### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by sturner** [fppt/jedis-mock#107]
I noticed no commits in over a year.  Is this library still supported?

**Comment by inponomarev** [comment]
It seems that @fppt disappeared :-(

Do we have many users for this library? It seems that [TestContainers](https://www.testcontainers.org/) or embedded Redis can be used for Redis testing. I personally gave up using jedis-mock in favour of TestContainers.

But the idea of this library is elegant. I think I can take over this project if @fppt doesn't appear, but I need to know if it's really useful: what are the use cases?

**Comment by burgjr** [comment]
We've found this library useful for cases where we don't have access to Docker on our development or test machines. We can't guarantee embedded Redis will always work as it requires access to certain standard libraries which aren't always available.

**Comment by fppt** [comment]
Hi Guys. My sincerest apologies for ghosting on this library. Thank you to @inponomarev for reaching out to me. I am happy for him to take over the project. So will be handing stuff over as time goes by

**Comment by fppt** [comment]
Release pipeline still works: https://github.com/fppt/jedis-mock/releases/tag/v0.17.0 . So i will try to clean some stuff up

**Comment by inponomarev** [comment]
Hi everyone, we made some progress and two new releases (0.17.0 and 0.18.0)
I think this issue can be closed now :-)
We will see how it's going to go now, but I think that the project is definitely revived and this issue can be closed now
