### ISSUE TITLE
Eval operation not supported

### ISSUE THREAD

**Issue by vepo** [fppt/jedis-mock#12]
I'm using jedis-mock with Redisson. When I call `bucket.getAndDelete()`, the lib is throwing the following exception:

```
15:49:42.811 [Thread-41] ERROR c.g.f.j.c.RedisOperationExecutor - Malformed request
java.lang.UnsupportedOperationException: Unsupported operation 'eval'
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:148)
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:166)
	at com.github.fppt.jedismock.RedisClient.run(RedisClient.java:48)
	at java.lang.Thread.run(Thread.java:748)
```

Is eval already supported?

How can I make it work?

**Comment by fppt** [comment]
`eval` is not yet supported. I will make sure to add it for the next release though. Thanks for raising the issue!

**Comment by fppt** [comment]
So this is turning out more time consuming than I though. i started working with this: https://github.com/luaj/luaj but have not had any luck so far. May have to wait a few releases until I figure this one out. Unless someone can suggest a good way to get java to interpret lua script

**Comment by kazetsukaimiko** [comment]
@fppt What was the issue with luaj integration?

You probably not only need the lua interpreter support, but also to expose any redis functionality to lua that is a part of the redis api.

**Comment by mnsrmov** [comment]
I'm having the same issue on the latest version in maven repository. Is `eval` still not supported?

**Comment by yang-yi-96** [comment]
I'm having the same issue on the latest version "1.0.5" in maven repository. Is eval still not supported?

**Comment by inponomarev** [comment]
@vepo @kazetsukaimiko @mnsrmov @yang-yi-96 great news, after 4 years since the first issue the Lua scripting with LuaJ is finally implemented

**Comment by yang-yi-96** [comment]
thank you very much
