### ISSUE TITLE
Unsupported operation 'scard'

### ISSUE THREAD

**Issue by meetPrasanth** [fppt/jedis-mock#21]
Actual:
Unsupported operation 'scard'; nested exception is redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'scard'

Expected:
"scard" operation expected to be work on jedis operation, which is available from redis version: 1.0.0

**Comment by fppt** [comment]
Addressed in linked PR and released as part of: https://github.com/fppt/jedis-mock/releases/tag/v0.1.10
