### ISSUE TITLE
ZREVRANGEBYSCORE doesn't work

### ISSUE THREAD

**Issue by newacct** [fppt/jedis-mock#218]
```
ZADD foo 1 one
ZADD foo 2 two
ZADD foo 3 three
ZREVRANGEBYSCORE foo 3 1
```
produces an empty array, when it should be `[three, two, one]`

**Comment by inponomarev** [comment]
Oops, forgot to write the test for this specific command

The issue was that, unlike `ZRANGEBYSCORE`, the order of arguments is different (from max to min, not from min to max)
