### ISSUE TITLE
INCR clears TTL

### ISSUE THREAD

**Issue by serandel** [fppt/jedis-mock#25]
From the Redis docs: 

> EXPIRE key seconds
> Available since 1.0.0.
> 
> Time complexity: O(1)
> 
> Set a timeout on key. After the timeout has expired, the key will automatically be deleted. A key with an associated timeout is often said to be volatile in Redis terminology.
> 
> The timeout will only be cleared by commands that delete or overwrite the contents of the key, including DEL, SET, GETSET and all the *STORE commands. This means that all the operations that conceptually alter the value stored at the key without replacing it with a new one will leave the timeout untouched. For instance, incrementing the value of a key with INCR, pushing a new value into a list with LPUSH, or altering the field value of a hash with HSET are all operations that will leave the timeout untouched.

Nevertheless, my tests are failing...

```     
        redis = RedisServer.newRedisServer();  // bind to a random port
        redis.start();
        jedis = new Jedis(redis.getHost(), redis.getBindPort());
        jedis.set(REDIS_KEY, "1");
        jedis.expire(REDIS_KEY, REMAINING_TTL);
        assertEquals(REMAINING_TTL, jedis.ttl(REDIS_KEY)); // OK
        jedis.incr(REDIS_KEY);
        assertEquals(REMAINING_TTL, jedis.ttl(REDIS_KEY)); // Got -1
```

Am I misunderstanding something?

**Comment by fppt** [comment]
Hmmm let me look into this. Might be a bug in the library.
