### ISSUE TITLE
Sets, Zsets and Lists exist even after all elements removed

### ISSUE THREAD

**Issue by newacct** [fppt/jedis-mock#312]
```
SADD foo bar
SREM foo bar
```
`EXISTS foo` returns 1 instead of 0, and `TTL foo` returns -1 instead of -2.

```
ZADD foo 42 bar
ZREM foo bar
```
`EXISTS foo` returns 1 instead of 0, and `TTL foo` returns -1 instead of -2.

```
lpush foo bar
lpop foo
```
`EXISTS foo` returns 1 instead of 0, and `TTL foo` returns -1 instead of -2.

**Comment by inponomarev** [comment]
Fixed in  v1.0.8
