### ISSUE TITLE
ConcurrentModificationException when deleting hashes with more than one field

### ISSUE THREAD

**Issue by patpod** [fppt/jedis-mock#34]
Deleting a hash with more than one field results in a `java.util.ConcurrentModificationException`.

This is due to the following piece of code in the class `ExpiringKeyValueStorage`:

```
public void delete(Slice key) {
        for (Slice key2 : values().row(key).keySet())
            delete(key, key2);
}

public void delete(Slice key1, Slice key2){
    Preconditions.checkNotNull(key1);
    Preconditions.checkNotNull(key2);
    values().remove(key1, key2);
    ttls().remove(key1, key2);
}
```
The iterator of the row's keySet complains because it is view of the values that get removed with `values().remove(key1, key2)`.

**Comment by fppt** [comment]
Being addressed (by you, thanks!!) in: https://github.com/fppt/jedis-mock/pull/35

**Comment by fppt** [comment]
Fix released in: https://github.com/fppt/jedis-mock/releases/tag/v0.1.11

Thank you for the contribution!
