### ISSUE TITLE
Support injected clock

### ISSUE THREAD

**Issue by oharaandrew314** [fppt/jedis-mock#343]
It would be nice to be able to inject a clock into the fake server so we can test expiry operations.

**Comment by inponomarev** [comment]
Clock injection is implemented in version 1.1.3

See [README ](https://github.com/fppt/jedis-mock?tab=readme-ov-file#clockinjection)for details

**Comment by oharaandrew314** [comment]
Does the server need to have the clock updated each time I wish to change the time?  Or will the server be reactive to the clock being mutated?  For example:

```kotlin
var time = Instant.EPOCH

server.setClock(object: Clock {
  override fun instant() = time
  ...
})

jedis.setex("key1", 20, "v1");
time += Duration.ofSeconds(30)
jedis.exists("key2") shouldBe false
```

**Comment by inponomarev** [comment]
Both approaches are possible, but please mark shared mutable `time` variable as `@Volatile`, as it will be read in a separate thread.

**Comment by oharaandrew314** [comment]
Oh, I see.  Thanks!
