### ISSUE TITLE
HDEL without fields behaves differently to Redis

### ISSUE THREAD

**Issue by SHildebrandt** [fppt/jedis-mock#371]
First of all, thanks for this library. It's easy to use and works great!

I found that `HDEL` works differently compared to Redis when no fields are passed by accident. While Jedis-Mock returns `0`, the original redis throws an error.
Would be cool if Jedis-Mock could also throw an error in this case to increase the chance that such a bug (in my application logic) can be found in unit tests.

**Comment by inponomarev** [comment]
Hi @SHildebrandt , please update to 1.0.12

**Comment by SHildebrandt** [comment]
awesome, thanks a lot! :)
