### ISSUE TITLE
NOPROTO Resp3 not supported by JedisMock

### ISSUE THREAD

**Issue by ngophuhung96** [fppt/jedis-mock#393]
I have a simple test case like below.
For an unknown reason, it always ran into [this line](https://github.com/fppt/jedis-mock/commit/b782e1082208b854946fc3383935af7b1fabeb14#diff-45dcc7d09ec27ba3fdde59fb9974949cb194d7f47ff8ce2b6383db8475b2cdcbR23) with version `1.0.13` (Version `1.0.12` still works well)

```java
package com.example.demo;

import com.github.fppt.jedismock.RedisServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.core.ValueOperations;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class RedisTest {
    @Autowired
    private RedisTemplate<String, String> redisTemplate;
    private RedisServer redisServer;

    @BeforeEach
    void startRedis() throws Exception {
        redisServer = RedisServer.newRedisServer(6379);
        redisServer.start();
    }

    @AfterEach
    void stopRedis() throws Exception {
        redisServer.stop();
    }

    @Test
    void test() {
        String key = "testKey";
        String value = "testValue";
        ValueOperations<String, String> valueOperations = redisTemplate.opsForValue();
        valueOperations.set(key, value);
        String result = valueOperations.get(key);
        assertEquals(value, result);
    }
}
```

I made an example project: https://github.com/ngophuhung96/demo
Can anyone help me with this? Thank you very much.

**Comment by inponomarev** [comment]
Thank you @ngophuhung96 for the request!

Jedis-mock indeed does not support Resp3 protocol, only Resp2. This error reply was added in 1.0.13 in order to support the fresh version of Lettuce driver (when it receives this error, it correctly fallbacks to Resp2). It seems that it works the other way in Spring's `RedisTemplate`. Thank you for the reproducer, expect a fixed version of JedisMock soon, meanwhile as a temporary workaround I would  recommend to use v. 1.0.12

**Comment by inponomarev** [comment]
@ngophuhung96 updating Lettuce version (adding `implementation 'io.lettuce:lettuce-core:6.3.0.RELEASE'` to `build.gradle` in your demo project) fixes the issue. 

Is it possible to update Lettuce in your project?

**Comment by ngophuhung96** [comment]
Hi @inponomarev . Thank you for the response. I tried updating the lettuce version and it works.
When I updated it, the implementation still returned true, but the error did not happen. I can't understand why. It's so weird.

```java
public Slice execute() {
        return this.protover != null && "3".equals(this.protover.toString()) ? Response.error("NOPROTO Resp3 not supported by JedisMock") : Response.array(Arrays.asList(Response.bulkString(Slice.create("proto")), Response.bulkString(Response.integer(2L))));
    }
```

**Comment by inponomarev** [comment]
Lettuce 6.3.0 uses `HELLO 3` command to determine if the instance of Redis is able to proceed using Resp3 protocol or not. 

Starting from 1.0.13 JedisMock replies with the error, as it is specifically handled by Lettuce which falls back to Resp2 protocol.


@ngophuhung96 , do I understand it right that updating Lettuce to 6.3.0 solves your problem and the issue can be closed? Let me know if you need further help!

**Comment by ngophuhung96** [comment]
@inponomarev Thank you for your very enthusiastic help, I closed the issue.
