### ISSUE TITLE
XAdd does not unblock XRead with BLOCK > 0

### ISSUE THREAD

**Issue by filipezlopez** [fppt/jedis-mock#452]
When XReading with BLOCK > 0 and other client XAdd to same stream, then XRead should be responded. Currently, only if BLOCK = 0 the XAdd causes to send response as it checks for updates and break while loop.

**Comment by 1BAH** [comment]
Thanks. I'm working on this problem now. I'll try to fix it as soon as possible.

**Comment by inponomarev** [comment]
@filipezlopez please update to v. 1.1.1
