### ISSUE TITLE
Support jdk17

### ISSUE THREAD

**Issue by BsoBird** [fppt/jedis-mock#487]
Since a large number of java-related communities are abandoning JAVA8, I'd like to confirm that jedis-mock supports JDK17+?

**Comment by inponomarev** [comment]
Our goal for JedisMock is to support all the Java version from Java 8 up to the most modern Java, which includes Java 17, of course. 

In case you face any specific issues related with Java 17, don't hesitate to open an issue, usually we fix such issues quite fast.

We're not dropping Java 8 support as there is still a large number of Java8 users (see e. g. [this report](https://newrelic.com/resources/report/2024-state-of-the-java-ecosystem?fbclid=IwZXh0bgNhZW0CMTAAAR27SaPabIq9tS5FVi8nvddX-zx0mxw900b9KyIpJGzuuU7qttQeFrDPIAk_aem_ZmFrZWR1bW15MTZieXRlcw))
