### ISSUE TITLE
unpack() in Lua scripts doesn't work

### ISSUE THREAD

**Issue by newacct** [fppt/jedis-mock#521]
```
EVAL "unpack({'foo', 'bar'})" 0
```
causes an error. This is probably because `unpack()` [was moved to](https://www.lua.org/manual/5.2/manual.html#8.2) `table.unpack()` in Lua 5.2, and [LuaJ](https://github.com/luaj/luaj) 3.x implements Lua 5.2. But [Redis uses](https://redis.io/docs/latest/develop/interact/programmability/eval-intro/) Lua 5.1.

**Comment by inponomarev** [comment]
Fixed in v 1.1.4
