### ISSUE TITLE
CLUSTER fails if server and client are bound to different addresses

### ISSUE THREAD

**Issue by antb88** [fppt/jedis-mock#537]
If redis mock and the client are bound to different ip addresses then CLUSTER command will return incorrect response likely causing clients to fail later on.

In both `slots` ([code](https://github.com/fppt/jedis-mock/blob/master/src/main/java/com/github/fppt/jedismock/operations/cluster/Cluster.java#L39)) and `nodes` ([code](https://github.com/fppt/jedis-mock/blob/master/src/main/java/com/github/fppt/jedismock/operations/cluster/Cluster.java#L50))`state.getHost()` is used which is eventually delegated to `RedisClient.getAddress()` which uses `socket.getInetAddress()` which will return the address the socket is connected to and not the local address. 

This will make the client to receive its own address instead of the server address and fail connecting to the node address.

**Comment by inponomarev** [comment]
Fixed in v. 1.1.5
