### ISSUE TITLE
Expire does not work as expected when data is set with hset()

### ISSUE THREAD

**Issue by pablito-dev** [fppt/jedis-mock#57]
Please note that I am not a Redis expert and that all the examples are in Kotlin.

In my application I got simple class to set hash which should expire after a given amount of time.

```
override fun method(key: String): String {
        return connectionPool.resource.use {
            it.hsetnx(key, HASH_CONST, UUID.randomUUID().toString())
            it.expire(key, EXPIRE_CONST)
            return it.hget(key, HASH_CONST)
        }
    }
```

I wrote a simple test which calls this method with given ID, then it waits more than the `EXPIRE_CONST` and then calls this method once again with same ID.

Result of this method should be different but it's the same.

After analyzing code of this library I saw that expire returns 0 instead of 1. I came to conclusion that the problem is `Slice.reserved()` call in `ExpiringKeyValueStorage.java:87`. When value is set using `hset()` the `key2` value should be set to hash key value, not the `"Reserved String In Jedis Mock"`.

One solution might be to iterate over hash keys and setting timeout for every one of them.

**Comment by pablito-dev** [comment]
I rewrote Kotlin to Java example for convenience:

```
public String method(final String key) {
        try (final Jedis connection = jedisPool.getResource()) {
            connection.hsetnx(key, HASH_CONST, UUID.randomUUID().toString());
            connection.expire(key, EXPIRE_CONST);
            return connection.hget(key, HASH_CONST)
        }
    }
```

**Comment by Savrov** [comment]
The same issue here.
My example code:
```
fun saveHMap(id: String, properties: HashMap<String, String>, ttl: Long? = null): Result<String> {
        if (properties.isNotEmpty()) {
            try {
                val result = jedis.hmset(id, properties)
                if (jedis.exists(id)) {
                    if (ttl != null && ttl > 0) {
                        return if (jedis.pexpire(id, ttl) == 1L) {
                            Result.Success("The timeout was set")
                        } else {
                            Result.Failure(NoSuchElementException("Key does not exist"))
                        }
                    }
                    return Result.Success(result)
                } else {
                    return Result.Failure(NoSuchElementException("Key was not found"))
                }
            } catch (ex: Exception) {
                return Result.Failure(ex)
            }
        } else {
            return Result.Failure(IllegalArgumentException("properties cant be empty"))
        }
    }
```
So I always end up with my own exception "Key does not exist" (code 0). Please note that I'm using **pexpire** function.
