### ISSUE TITLE
SimpleOperationsTest.sscanIterates is sometimes failing (flaky test)

### ISSUE THREAD

**Issue by mpetricek-corp** [fppt/jedis-mock#64]
When I try building the mock and running the test, one test case sometimes (in about 40% of the attempts) fails:

```
sscanIterates(com.github.fppt.jedismock.comparisontests.SimpleOperationsTest)  Time elapsed: 0.007 sec  <<< FAILURE!
org.junit.experimental.theories.internal.ParameterizedAssertionError: sscanIterates("redis.clients.jedis.Jedis@647e447" <from jedis[0]>)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.github.fppt.jedismock.comparisontests.SimpleOperationsTest.sscanIterates(SimpleOperationsTest.java:640)
```
When trying to use debugger, I found out that the test measures iterations in sscan, expecting it to take 5 iterations with 10 "page" size to fetch 45 elements.

However, sometimes I've seen in the debugger that higher amount of elements are returned per call (between 11 and 13 instead of 10), and as the sscan then completes in only 4 iterations instead of 5, it ends as assertion failure.

Possibly some race condition with other test case modifying default "page" size?

I am using OpenJDK 12 for the build.

**Comment by fppt** [comment]
Ya I have noticed this as well. Thanks for creating an issue for it. Seems to only happen to me locally. Will try to work it out.

**Comment by fppt** [comment]
Fixed! Thanks again @davidkus !
