### ISSUE TITLE
hsetnx is not returning 0 if field already exists

### ISSUE THREAD

**Issue by mpetricek-corp** [fppt/jedis-mock#97]
According to https://redis.io/commands/hsetnx HSETNX should return 0 if value to be set already exists (and thus was not set), but jedis-mock incorrectly returns 1 in this case.

There is a merge request that fixes that:
https://github.com/fppt/jedis-mock/pull/94

**Comment by inponomarev** [comment]
Thanks @mpetricek-corp for your contribution, sorry for such a long wait, your PR is merged now
